version: '3'
services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb"
    volumes:
      - ./dynamodb-data:/home/dynamodblocal/data

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    restart: always
    ports:
      - 8089:8001
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000

volumes:
  dynamodb-data:
