version: '3'
services:
  cassandra:
    image: cassandra:latest
    restart: always
    ports:
      - 9042:9042
      - 9160:9160
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCassandraCluster
      - CASSANDRA_SEEDS=cassandra
    volumes:
      - cassandra_data:/var/lib/cassandra

  cassandra-web:
    image: cassandra-web:latest
    restart: always
    ports:
      - 8089:3000
    environment:
      - CASSANDRA_HOSTS=cassandra
    depends_on:
      - cassandra

volumes:
  cassandra_data:
