version: '3'
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - 8089:8081
    environment:
      - REDIS_HOSTS=redis
    depends_on:
      - redis

volumes:
  redis_data:
